#ifndef __BIENUTIL_H
#define __BIENUTIL_H

// bienutil.h

#if !defined( _STLP_USE_NAMESPACES ) && !defined( __BIENUTIL_USE_NAMESPACE )
#define __BIENUTIL_GLOBALNAMESPACE
#endif

#define __STD _STLP_STD

#ifdef __BIENUTIL_GLOBALNAMESPACE
#define __BIENUTIL_BEGIN_NAMESPACE
#define __BIENUTIL_END_NAMESPACE
#define __BIENUTIL_USING_NAMESPACE
#define __BIENUTIL_NAMESPACE
#else //__BIENUTIL_GLOBALNAMESPACE
#ifndef __BIENUTIL_USE_NAMESPACE
#define __BIENUTIL_USE_NAMESPACE ns_bienutil
#endif //__BIENUTIL_USE_NAMESPACE
#define __BIENUTIL_BEGIN_NAMESPACE namespace __BIENUTIL_USE_NAMESPACE { using namespace std;
#define __BIENUTIL_END_NAMESPACE }
#define __BIENUTIL_USING_NAMESPACE using namespace __BIENUTIL_USE_NAMESPACE;
#define __BIENUTIL_NAMESPACE __BIENUTIL_USE_NAMESPACE::
#endif //__BIENUTIL_GLOBALNAMESPACE

#endif //!__BIENUTIL_H
